version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: crud_mongodb
    restart: always
    command: ["mongod","--logpath","/var/log/mongodb/mongod.log","--logappend","--bind_ip_all"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: crud_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - crud_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./crud-py
      dockerfile: Dockerfile
    container_name: crud_app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - environment/.env
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/crud_db"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - crud_network


  docs_service:
    build:
      context: ./docs-service
      dockerfile: Dockerfile
    container_name: crud_docs
    restart: always
    networks:
      - crud_network

  nginx:
    build:
      context: ./nginx-service
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-service/nginx.conf:/etc/nginx/nginx.conf
      - ./client/dist:/usr/share/nginx/html
      - ./environment/shop.key:/etc/nginx/shop.key:ro
      - ./environment/shop.crt:/etc/nginx/shop.crt:ro
    depends_on:
      - app
      - docs_service
    networks:
      - crud_network

volumes:
  mongodb_data:

networks:
  crud_network:
    driver: bridge
